# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Harbor agent wrappers that run vendor CLIs in Harbor local mode."""

from __future__ import annotations

import copy
import json
import os
import re
import shlex
from collections.abc import Callable
from pathlib import PurePosixPath
from typing import TYPE_CHECKING

from harbor.agents.installed.claude_code import ClaudeCode
from harbor.agents.installed.codex import Codex
from harbor.agents.installed.opencode import OpenCode
from harbor.models.trial.paths import EnvironmentPaths

if TYPE_CHECKING:
    from harbor.environments.base import BaseEnvironment

_CODEX_MODEL_ARG_RE = re.compile(r"(?P<prefix>(?:^|\s)--model(?:=|\s+))(?P<model>[^\s]+)(?P<suffix>(?=\s|$))")

_DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1"


def _codex_config_toml(base_url: str) -> str:
    """Generate Codex config for an OpenAI-compatible Responses API endpoint.

    The base URL comes from the caller's OPENAI_BASE_URL so an OSS user points
    Codex at their own OpenAI-compatible Responses provider; no endpoint is
    hardcoded.
    """
    return (
        "# Auto-generated by SkillEvaluator for OpenAI-compatible Responses routing.\n"
        'model_provider = "openai_compatible"\n\n'
        "[model_providers.openai_compatible]\n"
        'name = "OpenAI-compatible provider"\n'
        f'base_url = "{base_url}"\n'
        'env_key = "OPENAI_API_KEY"\n'
        'wire_api = "responses"\n'
    )


def _rewrite_launcher_segment(command: str, rewrite: Callable[[str], str]) -> str:
    """Apply launcher rewrites before the CLI ``--`` prompt separator only."""
    launcher, separator, prompt = command.partition(" -- ")
    if not separator:
        return rewrite(command)
    return f"{rewrite(launcher)}{separator}{prompt}"


class SkillEvaluatorLocalClaudeCode(ClaudeCode):
    """Claude Code wrapper that skips bootstrap install in local mode."""

    async def install(self, environment: BaseEnvironment) -> None:
        await self.exec_as_agent(environment, command="claude --version")

    def get_version_command(self) -> str | None:
        return "claude --version"

    async def exec_as_agent(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        timeout_sec: int | None = None,
    ):
        command = _rewrite_launcher_segment(
            command,
            lambda text: text.replace("--permission-mode=bypassPermissions", "--permission-mode=auto"),
        )
        return await super().exec_as_agent(
            environment,
            command=command,
            env=env,
            cwd=cwd,
            timeout_sec=timeout_sec,
        )


class SkillEvaluatorLocalCodex(Codex):
    """Codex wrapper that uses the managed local CLI and writes CODEX_HOME config."""

    # Harbor's upstream Codex integration uses /tmp/codex-home. In local mode
    # concurrent trials share the host /tmp, so use per-trial log paths instead.
    _REMOTE_CODEX_HOME = PurePosixPath(EnvironmentPaths.agent_dir / "codex-home")
    _REMOTE_CODEX_SECRETS_DIR = PurePosixPath(EnvironmentPaths.agent_dir / "codex-secrets")

    async def install(self, environment: BaseEnvironment) -> None:
        await self.exec_as_agent(environment, command="codex --version")

    def get_version_command(self) -> str | None:
        return "codex --version"

    def _preserve_gateway_model_name(self, command: str, env: dict[str, str] | None) -> str:
        """Undo Harbor's default Codex model truncation when routing through an OpenAI-compatible gateway."""
        model_name = str(self.model_name or "")
        if not model_name or "/" not in model_name or not (env or {}).get("OPENAI_BASE_URL"):
            return command

        short_model = model_name.rsplit("/", 1)[-1]

        def replace(match: re.Match[str]) -> str:
            if match.group("model") != short_model:
                return match.group(0)
            return f"{match.group('prefix')}{model_name}{match.group('suffix')}"

        return _rewrite_launcher_segment(command, lambda text: _CODEX_MODEL_ARG_RE.sub(replace, text))

    async def exec_as_agent(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        timeout_sec: int | None = None,
    ):
        command = _rewrite_launcher_segment(
            command,
            lambda text: text.replace(
                "/tmp/codex-secrets",
                self._REMOTE_CODEX_SECRETS_DIR.as_posix(),
            ),
        )
        command = self._preserve_gateway_model_name(command, env)
        return await super().exec_as_agent(
            environment,
            command=command,
            env=env,
            cwd=cwd,
            timeout_sec=timeout_sec,
        )

    async def run(self, instruction, environment: BaseEnvironment, context) -> None:  # type: ignore[no-untyped-def]
        config_path = self._REMOTE_CODEX_HOME / "config.toml"
        base_url = os.environ.get("OPENAI_BASE_URL") or _DEFAULT_OPENAI_BASE_URL
        config_text = _codex_config_toml(base_url).replace("'", "'\"'\"'")
        await self.exec_as_agent(
            environment,
            command=(
                f"mkdir -p {self._REMOTE_CODEX_HOME.as_posix()} "
                f"{self._REMOTE_CODEX_SECRETS_DIR.as_posix()} && "
                f"cat > {config_path.as_posix()} <<'EOF'\n"
                f"{config_text}"
                "EOF\n"
            ),
        )
        await super().run(instruction=instruction, environment=environment, context=context)


class SkillEvaluatorLocalOpenCode(OpenCode):
    """OpenCode wrapper that skips nvm/npm bootstrap in local mode."""

    _REMOTE_WORKSPACE = PurePosixPath("/workspace")

    async def install(self, environment: BaseEnvironment) -> None:
        await self.exec_as_agent(environment, command="opencode --version")

    def get_version_command(self) -> str | None:
        return "opencode --version"

    def _confined_project_env(self, env: dict[str, str] | None = None) -> dict[str, str]:
        confined = dict(env or {})
        confined.update(
            {
                "OPENCODE_FAKE_VCS": "git",
                "OPENCODE_TEST_HOME": self._REMOTE_WORKSPACE.as_posix(),
                "OPENCODE_DISABLE_PROJECT_CONFIG": "1",
            }
        )
        return confined

    def _nvidia_provider_config_command(self, model_id: str) -> str:
        config: dict[str, object] = {}
        if self.mcp_servers:
            mcp: dict[str, dict[str, object]] = {}
            for server in self.mcp_servers:
                if server.transport == "stdio":
                    cmd_list = [server.command, *server.args] if server.command else []
                    mcp[server.name] = {"type": "local", "command": cmd_list}
                else:
                    mcp[server.name] = {"type": "remote", "url": server.url}
            config["mcp"] = mcp

        config["provider"] = {
            "nvidia": {
                "npm": "@ai-sdk/openai-compatible",
                "name": "NVIDIA Build",
                "models": {model_id: {"name": model_id}},
                "options": {
                    "baseURL": os.environ.get("OPENAI_BASE_URL", ""),
                    "apiKey": "{env:OPENAI_API_KEY}",
                },
            }
        }
        config = self._deep_merge(copy.deepcopy(self._DEFAULT_CONFIG), config)
        config = self._deep_merge(config, self._opencode_config)
        escaped = shlex.quote(json.dumps(config, indent=2))
        return f"mkdir -p ~/.config/opencode && echo {escaped} > ~/.config/opencode/opencode.json"

    async def run(self, instruction, environment: BaseEnvironment, context) -> None:  # type: ignore[no-untyped-def]
        if not self.model_name or "/" not in self.model_name:
            raise ValueError("Model name must be in the format provider/model_name")

        provider, model_id = self.model_name.split("/", 1)
        confinement_env = self._confined_project_env()

        # OpenCode uses / as the project root when no VCS boundary exists. Set
        # up the isolated workspace before either the upstream provider path or
        # the NVIDIA-compatible path can launch it.
        await self.exec_as_agent(
            environment,
            command=f"git -C {self._REMOTE_WORKSPACE.as_posix()} init -q",
            env=confinement_env,
        )

        if provider != "nvidia":
            await super().run(instruction=instruction, environment=environment, context=context)
            return

        instruction = self.render_instruction(instruction)
        env = {key: os.environ[key] for key in ("OPENAI_API_KEY", "OPENAI_BASE_URL") if key in os.environ}
        env = self._confined_project_env(env)

        skills_command = self._build_register_skills_command()
        if skills_command:
            await self.exec_as_agent(environment, command=skills_command, env=env)

        await self.exec_as_agent(
            environment,
            command=self._nvidia_provider_config_command(model_id),
            env=env,
        )

        cli_flags = self.build_cli_flags()
        cli_flags_arg = (cli_flags + " ") if cli_flags else ""
        escaped_instruction = shlex.quote(instruction)
        await self.exec_as_agent(
            environment,
            command=(
                "if [ -f ~/.nvm/nvm.sh ]; then . ~/.nvm/nvm.sh; fi; "
                f"opencode run --model={self.model_name} --format=json "
                f"{cli_flags_arg}--thinking -- {escaped_instruction} "
                "2>&1 </dev/null | tee /logs/agent/opencode.txt"
            ),
            env=env,
        )

    async def exec_as_agent(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        timeout_sec: int | None = None,
    ):
        # Harbor's Docker image has GNU coreutils and a permissive OpenCode
        # wrapper, but trusted local hosts may have a stock CLI. Keep OpenCode's
        # JSON log capture while avoiding host-only argument failures before the
        # agent can run.
        command = command.replace(
            "| stdbuf -oL tee /logs/agent/opencode.txt",
            "| tee /logs/agent/opencode.txt",
        ).replace(" --dangerously-skip-permissions", "", 1)
        env = self._confined_project_env(env)
        return await super().exec_as_agent(
            environment,
            command=command,
            env=env,
            cwd=cwd,
            timeout_sec=timeout_sec,
        )


LOCAL_AGENT_IMPORT_PATHS = {
    "claude-code": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalClaudeCode",
    "codex": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalCodex",
    "opencode": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalOpenCode",
}
